package submitter

import json "github.com/goccy/go-json"

type Bucket int

const (
	EXCLUDED Bucket = iota
	DISPREFERRED_MMDBLOWN
	DISPREFERRED_LOWUPTIME
	DISPREFERRED_RECENTBADRESPONSE
	DISPREFERRED_RECENTTIMEOUT
	DISPREFERRED_RECENT5XX
	DISPREFERRED_RECENT4XX
	DISPREFERRED_SLOWRESPONSES
	NEUTRAL
	PREFERRED_BYCONFIG
)

func (bucket Bucket) MarshalJSON() ([]byte, error) {
	var s string
	switch bucket {
	case EXCLUDED:
		s = "EXCLUDED"
	case DISPREFERRED_MMDBLOWN:
		s = "DISPREFERRED_MMDBLOWN"
	case DISPREFERRED_LOWUPTIME:
		s = "DISPREFERRED_LOWUPTIME"
	case DISPREFERRED_RECENTBADRESPONSE:
		s = "DISPREFERRED_RECENTBADRESPONSE"
	case DISPREFERRED_RECENTTIMEOUT:
		s = "DISPREFERRED_RECENTTIMEOUT"
	case DISPREFERRED_RECENT5XX:
		s = "DISPREFERRED_RECENT5XX"
	case DISPREFERRED_RECENT4XX:
		s = "DISPREFERRED_RECENT4XX"
	case DISPREFERRED_SLOWRESPONSES:
		s = "DISPREFERRED_SLOWRESPONSES"
	case NEUTRAL:
		s = "NEUTRAL"
	case PREFERRED_BYCONFIG:
		s = "PREFERRED_BYCONFIG"
	default:
		s = "UNKNOWN"
	}

	return json.Marshal(s)
}
